"""empty message

Revision ID: 6931ec37084b
Revises: f51a06a79315
Create Date: 2024-11-01 21:24:13.695396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6931ec37084b'
down_revision = 'f51a06a79315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=False),
    sa.Column('people_count', sa.Integer(), nullable=False),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
